### ISSUE TITLE
Create stats page on website

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-website#147]
To give people an idea of network activity without having to wade into the spreadsheet.

Proposed metrics:
- overall volume
- fees
- bsq price + supply
- commits (?)
- number of contributors (?)

Anyone with ideas on which metrics should or shouldn't be included, please add.

**Comment by huey735** [comment]
I think that it'd be useful to also have a table/spreadsheet of the cost of a trade on Bisq:
* the trading fee for makers and takers
* the security deposit for makers (not necessary since it's not set in stone but rather set by the offer 
maker)
* nº of on chain transactions needed to finalize the trade for which the maker and taker are responsible for

**Comment by ManfredKarrer** [comment]
Trade fee for maker is 0.1% and for taker 0.3%.
Sellers security deposit is 0.5% of trade amount and buyers deposit default 2% but can be changed by maker.
The maker pays 1 times the miner fee for the maker fee tx. For the other 3 txs (taker fee tx, deposit tx and payout tx) the taker pays the miner fee.

I think that should be in the FAQ (I think it is but not sure if updated) but not subject to the stats page.

**Comment by huey735** [comment]
> Sellers security deposit is 0.5% of trade amount and buyers deposit default 2% but can be changed by maker.

@ManfredKarrer I think you meant offer-makers and offer-takers instead of sellers and buyers. We probably should promote this vocabulary instead. I think it's less confusing to understand from one's point of view if one's taking an existing offer or making a new one. On the other side it's easy to confuse whether one's buying or selling, because in any trade we're both buying and selling something. Also is the security deposit for offer-makers 0.5% of trade amount or 0.005btc no matter the trade amount?

It'd be useful to have those trades info plus trade limits in a table that'd be updated as changes are made:

**Fees per trade**

Categories | Offer-maker | Offer-taker | Version
------------ | ---------------- | ------------- | -------------
Trading fee | 0.1% of trade amount | 0.3% of trade amount | v.0.95
Security deposit* | 0.005btc | decided by offer-maker | v.0.95
Nº of miner's fee** | 1 | 3 | v.0.95


*this value is just a collateral and it's reimbursed to the traders and the end of trade.
**these numbers don't include the deposit and withdraw from and to an external wallet. 

**Trade Limits**

Payment method | 1st month (25%) | After |  Version
------------ | ---------------- | ------------- | -------------
Altcoins | 0.25btc | 1btc | v.0.95
Swish | 0.125btc | 0.5btc | v.0.95
SEPA | 0.0625btc | 0.25btc | v.0.95
Revolut | 0.04btc | 0.16btc | v.0.95

Here I put specific payment methods but we can aggregate several payment methods into "bank payments", "fintech solution", etc, and have those strings link to a page with all the payment methods under that category. We should also put a note saying to which version of the software these values apply to.

I think it is important to let newcomers get all the information needed to derive the costs of trading in the Bisq network in one place. These could all be in FAQ but I think a table is easier and faster to read, and to calculate one's own costs.

**Comment by ManfredKarrer** [comment]
@huey735 
No it is the security deposit for the buyer and for the seller. The maker or taker aspect is irrelevant. I know it is a bit confusing as the maker if he is the buyer he sets the desposit for himself.
The reasoning behind making the buyers security deposit adjustable is because only the buyer can "bail out" of the trade by not starting the fiat or altcoin payment. If price moves against him in volatile markets he has economic incentive to not do the trade but prefer to lose the security deposit.
For now we leave it to the maker to adjust that risk exposure as he usually know if the market is more volatile. If he is the buyer and he sets a high deposit he gives a signal to a taker that he is unlikely to "bail out".

In future we want to have it automated by the volatility of the coin, but that is a bit more effort, so atm we delegatet that work to the maker. But as I see (repeatadely) that it is very confusing we should prioritize that effort to get that set automated and the maker does not need to worry anymore about that.

**Comment by ManfredKarrer** [comment]
Regaring the account age:
For altcoins there is no account age, so you can trade 2 BTC from the beginning.
For fiat payment methods it depends on the payment methods chargback risk and there are 2 month until you get the full trade limit. First month 25%, second month 50%, and then 100% of the defined trade limit.

**Comment by huey735** [comment]
@ManfredKarrer you're right. This values regarding the trade don't seem to belong here in the Stats. I'd like your help understanding it better however over at https://bisq.community/t/clarification-on-fees-and-security-deposits/7234/6?u=huey

**Comment by arunasurya** [comment]
I assume you want to have these stats since the start of Bisq in April 2016? For the contributors, we have data since December 2017 but it would be nice to see that as well. Perhaps, a breakdown of contributors by roles? Maybe have two subparts: Bisq metrics and DAO metrics?

**Comment by pedromvpg** [comment]
Stats page
https://www.figma.com/proto/D9XHYXcNcobektGe5DpzAhVl/New-Pages?node-id=3%3A1&viewport=-664%2C-169%2C0.357336&scaling=min-zoom

![Stats-Desktop](https://user-images.githubusercontent.com/807505/55686194-1b1f9b00-592c-11e9-8159-77fcc081ad59.png)

Is this the right list of data to be displayed? If not is there a consolidated list I can reference?

**Comment by m52go** [comment]
Completed with https://github.com/bisq-network/bisq-website/pull/156. Closing.
