### ISSUE TITLE
[Proposal] Translate Bisq software images in the homepage

### ISSUE THREAD

**Issue by huey735** [bisq-network/bisq-website#207]
To add to the translation of the website, we can also translate the images of the software in the homepage. I'm thinking of using screenshots of the USD market as a standard for every language. What do you think? @m52go @mpolavieja 
Bellow is the comparison of the current images in the website and their current form in the software in English

### Trades
![bisq_screen1](https://user-images.githubusercontent.com/44140017/63517799-99e63080-c4e7-11e9-9aaa-4336cca1c442.png)
![bisq_screen1_new](https://user-images.githubusercontent.com/44140017/63517815-9fdc1180-c4e7-11e9-9c6a-9ccb3fdc9aa4.png)

### Offer book
![bisq_screen0](https://user-images.githubusercontent.com/44140017/63517802-9a7ec700-c4e7-11e9-9e33-1d83efc4efc1.png)
![bisq_screen0_new](https://user-images.githubusercontent.com/44140017/63517816-a074a800-c4e7-11e9-88f2-5483d9361123.png)

**Comment by m52go** [comment]
@huey735 should be ok, but I wonder if the new images are too complex. It looks like the old images are mockups of the UI, instead of screenshots of the actual UI, so they seem to hide some of the real UI's perceived complexity (e.g., small numbers, lots of rows, etc).

**Comment by huey735** [comment]
Yes, @m52go the original images are easier on the eyes but I don't think the new are too 'busy'.
And I can't render the images in the same resolution as the originals. I hope it's ok
orginal - 2400 x 1378
new - 1566 x 899

**Comment by m52go** [comment]
Wow, I could only get 1200 × 747 and I'm on a pretty big 4k monitor. Weird. Anyway yeah maybe try it and see how it looks? It might not be a big deal after all.

**Comment by m52go** [comment]
@huey735 would you like to take care of this? #230 makes it straightforward...just replace the placeholders referenced there with localized screenshots.

**Comment by huey735** [comment]
@m52go I got 1566 x 899 screenshots if full view which is kind of ugly as it adds to many rows and I feel like unbalances the picture. At Bisq's default size I get 1200 × 747, 1200 × 680 when I remove the top and bottom info bars.

These are what mine look compare @wiz's who's rendering them close to the current resolution. I've chosen to render them all for the USD market to keep consistency.

![bisq-japanese-market](https://user-images.githubusercontent.com/44140017/64446458-c0ec5700-d0d0-11e9-9104-a8ae0e364030.png)
![bisq-japanese-market](https://raw.githubusercontent.com/bisq-network/bisq-website/e2a196bfa7ab1a2aee6deab19daecb1755347e47/ja/images/bisq_screen0.png)

![bisq-japanese-trades](https://user-images.githubusercontent.com/44140017/64446456-c053c080-d0d0-11e9-8ab7-080aa88224c0.png)
![bisq-japanese-market](https://raw.githubusercontent.com/bisq-network/bisq-website/e2a196bfa7ab1a2aee6deab19daecb1755347e47/ja/images/bisq_screen1.png)

**Comment by wiz** [comment]
Oh, I didn't know you had an issue for this, yeah I actually increased the size of the top main navigation strings in the Bisq app for Japanese locale in preparation for taking the screenshot on bisq.network/ja since I wanted to polish it up a bit. Let me know if you need help taking sexy localized screenshots for the homepage.

**Comment by huey735** [comment]
@wiz I'd pretty much appreciate your sexy screenshots.
Can we agree on a standard? For simplicity and cohesion I was thinking of taking screenshots for the USD market for all markets. And we'd exclude the top and bottom info bars from the screenshot.
You've excluded the navbar from your bisq_screen1.png. I'd prefer it back.

**Comment by wiz** [comment]
@huey735 The goal here is not mere translation, but complete localization. Let me explain:

Localization is an art, of much more than just translating content, it is the process of completely adapting and optimizing UI/UX for the intended target audience of users. It's usually done by an expert of that locality who knows what users will expect and how they will behave. For example, for users in Japan, of course they will want the Japanese language, but more importantly, I know they will want to trade on the JPY market, and they will want to use a Japan Bank Transfer payment method.

So please understand it is counter-intuitive to the localization process to always show the USD market in screenshots, even to people who are probably not interested in USD. The correct choice for Japan users is to show them screenshots of the JPY market, but since the JPY market is not mature yet, for now I decided to use Japanese screenshots of the app displaying the most liquid fiat market EUR. What screenshots are best to display to a particular locale is a decision that the contributor doing those localizations should make.

This is also why I didn't just blindly take screenshots of each app in each language and throw them on the website in my original PR; this is the job for the individual localization experts because there are many important decisions to make along the way. So to clarify, I'm not offering to take screenshots, I could have done that already - I'm offering to help you take nice screenshots of what exactly you think should be displayed to your users, as in technical support if you need it, since you had commented that the screenshots you had taken were low quality.

So hit me up on slack if you need help taking sexy screenshots :wink:

**Comment by wiz** [comment]
@huey735 hey buddy, did you still want to do this? 😅

**Comment by gilsanjuan** [comment]
Hey guys I can help with this task @wiz

**Comment by m52go** [comment]
@gilsanjuan sure, why not. Can re-assign this to you if you'd like to knock it out.

**Comment by gilsanjuan** [comment]
Hey guys, I made render on Sketch, I mixed current home image with current Bisq UI,  tell me what do you thing?

SVG file here -> https://drive.google.com/file/d/1vxlSizSE1uQEAq50Nx7jisQtGAvuSbA9/view?usp=sharing

![Bisq UI EN](https://user-images.githubusercontent.com/4778093/67543927-244e3a80-f6b9-11e9-8c3f-ae5285943cbe.png)

**Comment by m52go** [comment]
Completed with #278.
