### ISSUE TITLE
Remove localhost links

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-website#264]
There are several references to localhost, which is causing broken links.

https://github.com/bisq-network/bisq-website/search?q=%22localhost%3A4001%22&unscoped_q=%22localhost%3A4001%22

**Comment by erciccione** [comment]
The additional issues is that the link is hardcoded in the LANG.yml files for all languages. We have `localhost` showing in some Spanish and German pages, but for the other languages we have the value that was originally in the `en.yml`, so basically a link to the English section of the website.
https://github.com/bisq-network/bisq-website/blob/master/_data/ja.yml#L56

IMO there are 2 ways to fix this:

- Harcode the link to the related language in LANG.yml. So in the example above, the link could be `<a href="https://bisq.network/ja/community/">`
- Split the sentences in more variables, leaving the link out and adding it to the layout. This way every language would pick the correct link for them.

The last option is time consuming and requires small changes to the base layout and to add some variables, but resolves the problem in the long term. The first option is quicker to implement and doesn't require any important change, but will require more attention from future translators (since they will copy and paste that section, they have to be reminded that they need to adapt the link adding the code for thir language).

I think the first option could be good enough in our case.

**Comment by m52go** [comment]
Fixed with #266.
