### ISSUE TITLE
faq and gender

### ISSUE THREAD

**Issue by ghost** [bisq-network/bisq-website#56]
The faq mentions:

> If collusion is found to have taken place, the misbehaving arbitrator will lose her BSQ bond. This puts the arbitrator at a significant loss, as her BSQ bond was much more than she made by being dishonest.

Is there any reason to use "her" and "she" ? or it's just some wink ?

I'm not at all shocked, just asking.

**Comment by ManfredKarrer** [comment]
I think its the political correct gender case, but I am not a native speaker....

**Comment by cbeams** [comment]
I consistently use the gender-neutral "singular they" in all of my arbitration communications, e.g. "The seller says *they* have not received your payment". I do this because I often have no way of knowing the gender of either party, and even if it is possible to infer it from first/last name information, using the singular they makes everything simple and consistent. See https://en.wikipedia.org/wiki/Singular_they.

I would prefer to do away with using "she/her" instead of "him/his". To me, this sort of thing always comes off as a transparent and clumsy attempt to be politically correct, and only ends up distracting from whatever essential communication is trying to be made.

So I would suggest changing this language in the FAQ (and elsewhere) to use the singular they. It solves the gender problem nicely, and trips up only the most pedantic of language purists who try to claim that the singular they is "improper English" even though it has long been in widespread use.

**Comment by cbeams** [comment]
Closing as answered. @HarryMacfinned, feel free to submit a pull request to fix this, thanks.
