### ISSUE TITLE
ToS is showing "company_short_name" rather than.. Well the company short name

### ISSUE THREAD

**Issue by dginovker** [bisq-network/bisq-website#92]
As seen here: https://bisq.community/tos

Lines such as: "...you agree to pay company_short_name the monthly or annual subscription fees indicated" are happening.

**Comment by ManfredKarrer** [comment]
@alexej996 Can you have  a look? Wondering if it is needed to have those tos and how that fit to bisq as OS project? But no hi prio.... friction with legacy world...

**Comment by alexej996** [comment]
Oh yeah, that is just there by default. I just left it how it was before I took over the forum.
I have no idea what I could put there, if anything is necessary. Bisq isn't a company, so it is probably best to just remove ToS for the time being.

Alternatively I could try writing a custom ToS, which would claim that all content shared is licensed under GPLv3 or something, otherwise there really ins't anything interesting we could put there. Bitcointalk has no ToS as far as I can tell, so really it wouldn't make much sense for us to add one either, I guess.

**Comment by alexej996** [comment]
Edited it a bit, it should be more applicable to us now.
